######################################################################
#
# File name : tb_light_eye_v2_13_compile.do
# Created on: Mon Aug 22 21:02:44 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work   \
"../../../../src/gray_driv.v" \

vlog  -incr -mfcu -sv -work   \
"../../../../src/tb_light_eye_v2_13.sv" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

